name: Markdown Lint
on: [push, pull_request]
jobs:
  lint-changelog:
    name: Lint changelog file
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Lint changelog file
      uses: docker://avtodev/markdown-lint:v1
      with:
        args: '../CHANGELOG.md ../README.md ../CODE_OF_CONDUCT.md'