name: Format markdown files
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  markdown-lint:
    name: Markdown Lint
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      
      - name: Format files
        run: npx prettier . --check
